version: 1.0.{build}
before_build:
- cmd: nuget restore SWapi-CSharp.sln
build:
  project: SWapi-CSharp.sln
  parallel: true
  verbosity: minimal
branches:
  only:
    - master
# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release
test_script:
- ps: >-
    vstest.console.exe /inIsolation /Enablecodecoverage .\SWapi-CSharp\SWapi-CSharpTests\bin\Release\SWapi-CSharpTests.dll /Settings:CodeCoverage.runsettings
    $coverageFilePath = Resolve-Path -path "TestResults\*\*.coverage"
    $coverageFilePath = $coverageFilePath.ToString()
    if(Test-Path .\coverage.coveragexml){ rm .\coverage.coveragexml }
    ."C:\Program Files (x86)\Microsoft Visual Studio 12.0\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe" analyze /output:coverage.coveragexml "$coverageFilePath"

    Push-AppveyorArtifact coverage.coveragexml

    $coveralls = (Resolve-Path "src/packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()

    & $coveralls --dynamiccodecoverage -i coverage.coveragexml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID --useRelativePaths -o cov.json

    Push-AppveyorArtifact cov.json
